### ISSUE TITLE
Add support for more data types

### ISSUE THREAD

**Issue by Am0stafa** [orosmatthew/hydrogen-cpp#16]

**Comment by laurinyev** [comment]
this is a tutorial series on YT(so ofc there will be more types)
you dum-dum

**Comment by laurinyev** [comment]
read the F-ing readme

**Comment by laurinyev** [comment]
@orosmatthew  I think you should disable issues, since every single one has been pure garbage so fare

**Comment by Am0stafa** [comment]
> this is a tutorial series on YT(so ofc there will be more types) you dum-dum

I am suggesting video idea dum-$ss

**Comment by zedritsch** [comment]
Actually, that was the first issue. But disabling pull requests might be a good idea
